### ISSUE TITLE
re-api returns error 503

### ISSUE THREAD

**Issue by jor70** [adsblol/status#107]
re-api.adsb.lol 503 Service Temporarily Unavailable

**Comment by iakat** [comment]
related to https://github.com/alpinelinux/docker-alpine/issues/383

**Comment by iakat** [comment]
@jor70 should be solved now, in the future IRC will probably get a quicker look.

**Comment by jor70** [comment]
Awesome, thanks El 27/3/24, 18:43 Katia Esposito ***@***.***> escribió:

   
  @jor70 should be solved now, in the future IRC will probably get a quicker look.

**Comment by jor70** [comment]
503 error happening again
 


should be solved now, in the future IRC will probably get a quicker look.
